package com.epam.pdp.sto.thinkinginjava.arrays.exercises;

import java.util.Arrays;
import java.util.Random;

import static com.epam.pdp.sto.thinkinginjava.arrays.exercises.Ex3.printArr;

/**
 * Exercise 4: (2) Repeat the previous exercise for a three-dimensional array.
 */
public class Ex4 {
    //a method that creates and initializes a threedimensional array of double:
    public static double[][][] creatInitial3Darr(int arrSize1,int arrSize2,int arrSize3, double start1, double end1) {
        Random rand = new Random();
        double [][][] arrD = new double[arrSize1][arrSize2][arrSize3];
        for (int ind = 0; ind < arrSize3; ind++) {
            for (int ind1 = 0; ind1 < arrSize2; ind1++) {
            for (int ind2 = 0; ind2 < arrSize1; ind2++) {
                arrD[ind2][ind1][ind] = start1 + (end1 - start1) * rand.nextDouble();
            }
            }
        }
        return arrD;
    }
    //method that will print the array generated by the first method:
    public static void printArr(double[][][] arr3D) {
        System.out.println("double[][][] = " + Arrays.deepToString(arr3D));
    }

       public static void main(String[] args) {
        double[][][] arr1 = creatInitial3Darr(2,3,2,3.1,8.7);
        double[][][] arr2 = creatInitial3Darr(3,2,1,0.1,0.3);
        printArr(arr1);
        printArr(arr2);

    }
}
/**Output:
 *double[][][] = [[[3.590328955085411, 6.374379852621837], [3.842311480717377, 5.975336803617481],
 * [8.62205444357361, 6.932848492974292]], [[8.558263488675882, 4.202156203880044],
 * [4.542635013726612, 7.777735754318185], [6.239594453847383, 7.1971626907014805]]]
 double[][][] = [[[0.10925520467017646], [0.18935526126783028]], [[0.18848737961786363],
 [0.21150243981110958]], [[0.12326414763721068], [0.20967555669942378]]]
 */

